# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tV5VrgWr2pWqLlX72wQL3gs-dsZ_XHYE
"""

import streamlit as st
import cv2
import numpy as np
from PIL import Image

st.set_page_config(page_title="Pencil Sketch App", layout="centered")

st.title("🎨 Pencil Sketch App")
st.write("Upload an image and convert it into a pencil sketch using OpenCV.")

# Upload image
uploaded_file = st.file_uploader("Choose an image...", type=["jpg", "jpeg", "png"])

if uploaded_file is not None:
    # Read image
    image = Image.open(uploaded_file)
    image_np = np.array(image)

    # Convert to BGR (if needed)
    if image_np.shape[-1] == 4:  # RGBA -> RGB
        image_np = cv2.cvtColor(image_np, cv2.COLOR_RGBA2RGB)
    image_bgr = cv2.cvtColor(image_np, cv2.COLOR_RGB2BGR)

    # Convert to grayscale
    gray_image = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2GRAY)

    # Invert
    inverted_image = 255 - gray_image

    # Blur
    blurred = cv2.GaussianBlur(inverted_image, (21, 21), 0)

    # Invert the blurred
    inverted_blur = 255 - blurred

    # Create pencil sketch
    pencil_sketch = cv2.divide(gray_image, inverted_blur, scale=256.0)

    # Show results
    st.subheader("📌 Original Image")
    st.image(image, use_column_width=True)

    st.subheader("✏️ Pencil Sketch")
    st.image(pencil_sketch, use_column_width=True, clamp=True)

    # Download button
    result = Image.fromarray(pencil_sketch)
    st.download_button(
        label="💾 Download Sketch",
        data=result.tobytes(),
        file_name="pencil_sketch.jpg",
        mime="image/jpeg"
    )